# rocprofiler-systems
[components.lib."profiler/rocprofiler-systems/stage"]
include = [
  "libexec/rocprofiler-systems/**",
  "lib/python*/**",
]
exclude = [
  "share/rocprofiler-systems/tests/**",
  "share/rocprofiler-systems/examples/**",
]
[components.run."profiler/rocprofiler-systems/stage"]
include = [
  "bin/**",
  "share/rocprofiler-systems/**",
  "share/modulefiles/rocprofiler-systems/**",
]
exclude = [
  "share/rocprofiler-systems/tests/**",
  "share/rocprofiler-systems/examples/**",
]
[components.dbg."profiler/rocprofiler-systems/stage"]
[components.dev."profiler/rocprofiler-systems/stage"]
[components.doc."profiler/rocprofiler-systems/stage"]
include = [
  "share/doc/rocprofiler-systems/**"
]
# Test binaries lie under rocprofiler-systems-examples artifact
[components.test."profiler/rocprofiler-systems/stage"]
include = [
  "share/rocprofiler-systems/tests/**",
]
