# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Build Windows Artifacts

on:
  workflow_dispatch:
    inputs:
      amdgpu_families:
        type: string
        default: gfx1151
      artifact_group:
        type: string
        default: gfx1151
      build_variant_label:
        type: string
        description: "A label for the build variant (ex: 'release', 'asan')"
        default: "release"
      build_variant_suffix:
        type: string
        description: "The build variant suffix (ex: 'asan' suffix -> 'gfx94X-dcgpu-asan')"
        default: ""
      build_variant_cmake_preset:
        type: string
        description: "The name of the cmake preset to use for this build variant, matching an entry in CMakePresets.json (ex: 'linux-release-asan')"
        default: ""
      package_version:
        type: string
        default: ADHOCBUILD
      expect_failure:
        type: boolean
      extra_cmake_options:
        type: string

  workflow_call:
    inputs:
      package_version:
        type: string
        default: ADHOCBUILD
      amdgpu_families:
        type: string
      artifact_group:
        type: string
      build_variant_label:
        type: string
      build_variant_suffix:
        type: string
      build_variant_cmake_preset:
        type: string
      expect_failure:
        type: boolean
      extra_cmake_options:
        type: string

permissions:
  contents: read

jobs:
  build_windows_artifacts:
    name: Build ${{ inputs.build_variant_label }} (xfail ${{ inputs.expect_failure }})
    runs-on: azure-windows-scale-rocm
    continue-on-error: ${{ inputs.expect_failure }}
    timeout-minutes: 720 # 12 hour timeout
    permissions:
      id-token: write
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
    env:
      BUILD_DIR: B:\build
      CACHE_DIR: "${{github.workspace}}/.cache"
      CCACHE_CONFIGPATH: "${{github.workspace}}/.ccache/ccache.conf"
      TEATIME_FORCE_INTERACTIVE: 0
      AMDGPU_FAMILIES: ${{ inputs.amdgpu_families }}
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12

      - name: Install python deps
        run: |
          pip install -r requirements.txt

      - name: Install requirements
        # The first two lines removes the default commmunity feed and uses the internal proxy feed
        run: |
          choco source disable -n=chocolatey
          choco source add -n=internal -s http://10.0.167.96:8081/repository/choco-group/ --priority=1
          choco install --no-progress -y ccache
          # ninja pinned due to a bug in the 1.13.0 release:
          # https://github.com/ninja-build/ninja/issues/2616
          choco install --no-progress -y ninja --version 1.12.1
          choco install --no-progress -y strawberryperl
          echo "$PATH;C:\Strawberry\c\bin" >> $GITHUB_PATH
          choco install --no-progress -y awscli
          choco install --no-progress -y pkgconfiglite
          echo "$PATH;C:\Program Files\Amazon\AWSCLIV2" >> $GITHUB_PATH

      - uses: iterative/setup-dvc@4bdfd2b0f6f1ad7e08afadb03b1a895c352a5239 # v2.0.0
        with:
          version: '3.62.0'

      # After other installs, so MSVC get priority in the PATH.
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Runner health status
        run: |
          python ./build_tools/health_status.py

      - name: Setup ccache
        run: |
          python ./build_tools/setup_ccache.py \
            --config-preset "github-oss-dev" \
            --dir "$(dirname $CCACHE_CONFIGPATH)" \
            --local-path "$CACHE_DIR/ccache" \
            --log-dir "${BUILD_DIR}/logs/ccache"

      - name: Fetch sources
        timeout-minutes: 30
        run: |
          git config fetch.parallel 10
          git config --global core.symlinks true
          git config --global core.longpaths true
          python ./build_tools/fetch_sources.py --jobs 12

      - name: Configure Projects
        env:
          cmake_preset: ${{ inputs.build_variant_cmake_preset }}
          amdgpu_families: ${{ inputs.amdgpu_families }}
          package_version: ${{ inputs.package_version }}
          extra_cmake_options: ${{ inputs.extra_cmake_options }}
        run: |
          python3 build_tools/github_actions/build_configure.py

      - name: Build therock-artifacts and therock-dist
        run: |
          cmake --build "${{ env.BUILD_DIR }}" --target therock-artifacts therock-dist -- -k 0

      - name: Report
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          if [ -d "${{ env.BUILD_DIR }}" ]; then
            echo "Build dir:"
            echo "------------"
            ls -lh "${{ env.BUILD_DIR }}"
            echo "Artifacts:"
            echo "----------"
            du -h -d 1 "${{ env.BUILD_DIR }}"/artifacts
            echo "CCache Stats:"
            echo "-------------"
            ccache -s -v
          else
            echo "[ERROR] Build directory ${{ env.BUILD_DIR }} does not exist. Skipping report!"
            echo "        This should only happen if the CI is cancelled before the build step."
            exit 1
          fi

      - name: "Build size report"
        if: always()
        shell: powershell
        run: |
          $fs = Get-PSDrive -PSProvider "FileSystem"
          $fsout = $fs | Select-Object -Property Name,Used,Free,Root
          $fsout | % {$_.Used/=1GB;$_.Free/=1GB;$_} | Write-Host
          get-disk | Select-object @{Name="Size(GB)";Expression={$_.Size/1GB}} | Write-Host

      - name: Configure AWS Credentials
        if: ${{ always() }}
        uses: ./.github/actions/configure_aws_artifacts_credentials

      - name: Push artifacts
        run: |
          python build_tools/artifact_manager.py push \
            --run-id ${{ github.run_id }} \
            --build-dir=${{ env.BUILD_DIR }} \
            --stage=all

      - name: Post Build Upload
        if: always()
        run: |
          python3 build_tools/github_actions/post_build_upload.py \
            --run-id ${{ github.run_id }} \
            --artifact-group ${{ inputs.artifact_group }} \
            --build-dir ${{ env.BUILD_DIR }} \
            --upload
