# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Release Windows packages

on:
  # Trigger from another workflow (typically to build dev packages and then test them)
  workflow_call:
    inputs:
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        type: string
        default: "dev"
      package_suffix:
        type: string
      s3_subdir:
        description: "Subdirectory to push the Python packages"
        type: string
        default: "v2"
      s3_staging_subdir:
        description: "Staging subdirectory to push the packages"
        type: string
        default: "v2-staging"
      families:
        description: "Comma separated list of AMD GPU families, e.g. `gfx94X,gfx103x`, or empty for the default list"
        type: string
      prerelease_version:
        description: "(Optional) Number of the prerelease"
        type: string
      extra_cmake_options:
        description: "Extra options to pass to the CMake configure command"
        type: string
      repository:
        description: "Repository to checkout. Otherwise, defaults to `github.repository`."
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
  # Trigger manually (typically to test the workflow or manually build a release [candidate])
  workflow_dispatch:
    inputs:
      release_type:
        description: The type of release to build ("dev", "nightly", or "prerelease"). All developer-triggered jobs should use "dev"!
        type: string
        default: "dev"
      package_suffix:
        type: string
      s3_subdir:
        description: "Subdirectory to push the Python packages"
        type: string
        default: "v2"
      s3_staging_subdir:
        description: "Staging subdirectory to push the packages"
        type: string
        default: "v2-staging"
      families:
        description: "A comma separated list of AMD GPU families, e.g. `gfx94X,gfx103x`, or empty for the default list"
        type: string
        default: "gfx110X"
      prerelease_version:
        description: "(Optional) Number of the prerelease"
        type: string
      extra_cmake_options:
        description: "Extra options to pass to the CMake configure command"
        type: string

  # Trigger on a schedule to build nightly release candidates.
  schedule:
    # Runs at 02:00 AM UTC, which is 7:00 PM PST (UTC-8)
    - cron: '0 02 * * *'

permissions:
  contents: read

run-name: Release Windows packages (${{ inputs.release_type || 'nightly' }}, ${{ inputs.families || 'default' }})

jobs:
  setup_metadata:
    if: ${{ github.repository_owner == 'ROCm' || github.event_name != 'schedule' }}
    runs-on: ubuntu-24.04
    env:
      release_type: ${{ inputs.release_type || 'nightly' }}
    outputs:
      version: ${{ steps.rocm_package_version.outputs.rocm_package_version }}
      release_type: ${{ env.release_type }}
      package_targets: ${{ steps.configure.outputs.package_targets }}
      cloudfront_url: ${{ steps.release_information.outputs.cloudfront_url }}
      cloudfront_staging_url: ${{ steps.release_information.outputs.cloudfront_staging_url }}
      s3_subdir_tar: ${{ steps.release_information.outputs.s3_subdir_tar }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12

      - name: Compute package version
        id: rocm_package_version
        run: |
          python ./build_tools/compute_rocm_package_version.py \
            --release-type=${{ env.release_type }} \
            --prerelease-version=${{ inputs.prerelease_version }}

      - name: Set variables for nightly release
        if: ${{ env.release_type == 'nightly' }}
        run: |
          echo "tmp_cloudfront_url=https://rocm.nightlies.amd.com/v2" >> $GITHUB_ENV
          echo "tmp_cloudfront_staging_url=https://rocm.nightlies.amd.com/v2-staging" >> $GITHUB_ENV
          echo "tmp_s3_subdir_tar=''" >> $GITHUB_ENV

      - name: Set variables for prerelease
        if: ${{ env.release_type == 'prerelease' }}
        run: |
          echo "tmp_cloudfront_url=https://rocm.prereleases.amd.com/whl" >> $GITHUB_ENV
          echo "tmp_cloudfront_staging_url=https://rocm.prereleases.amd.com/whl-staging" >> $GITHUB_ENV
          echo "tmp_s3_subdir_tar=v3/tarball/" >> $GITHUB_ENV

      - name: Set variables for development release
        if: ${{ env.release_type == 'dev' }}
        run: |
          echo "tmp_cloudfront_url=https://rocm.devreleases.amd.com/v2" >> $GITHUB_ENV
          echo "tmp_cloudfront_staging_url=https://rocm.devreleases.amd.com/v2-staging" >> $GITHUB_ENV
          echo "tmp_s3_subdir_tar=''" >> $GITHUB_ENV

      - name: Generate release information
        id: release_information
        run: |
          echo "cloudfront_url=${tmp_cloudfront_url}" >> $GITHUB_OUTPUT
          echo "cloudfront_staging_url=${tmp_cloudfront_staging_url}" >> $GITHUB_OUTPUT
          echo "s3_subdir_tar=${tmp_s3_subdir_tar}" >> $GITHUB_OUTPUT

      - name: Generating package target matrix
        id: configure
        env:
          AMDGPU_FAMILIES: ${{ inputs.families }}
          THEROCK_PACKAGE_PLATFORM: "windows"
        run: python ./build_tools/github_actions/fetch_package_targets.py

  windows_packages:
    name: ${{ matrix.target_bundle.amdgpu_family }}::Build Windows
    runs-on: ${{ github.repository_owner == 'ROCm' && 'azure-windows-scale-rocm' || 'windows-2022' }}
    continue-on-error: ${{ matrix.target_bundle.expect_failure == true }} # for GPU families that are flaky, we mark as xfail
    timeout-minutes: 720 # 12 hour timeout
    needs: [setup_metadata]
    permissions:
      contents: write
      actions: write # Added permission to trigger workflows
      id-token: write # Added permission for AWS S3 upload
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        target_bundle: ${{ fromJSON(needs.setup_metadata.outputs.package_targets) }}
    env:
      TEATIME_LABEL_GH_GROUP: 1
      BUILD_DIR: B:\build
      CACHE_DIR: "${{github.workspace}}/.cache"
      CCACHE_CONFIGPATH: "${{github.workspace}}/.ccache/ccache.conf"
      DIST_ARCHIVE: "B:/build/artifacts/therock-dist-windows-${{ matrix.target_bundle.amdgpu_family }}${{ inputs.package_suffix }}-${{ needs.setup_metadata.outputs.version }}.tar.gz"
      RELEASE_TYPE: "${{ needs.setup_metadata.outputs.release_type }}"
      S3_BUCKET_TAR: "therock-${{ needs.setup_metadata.outputs.release_type }}-tarball"
      S3_SUBDIR_TAR: ${{ needs.setup_metadata.outputs.s3_subdir_tar }}
      S3_BUCKET_PY: "therock-${{ needs.setup_metadata.outputs.release_type }}-python"
      S3_SUBDIR: ${{ inputs.s3_subdir || 'v2' }}
      S3_STAGING_SUBDIR: ${{ inputs.s3_staging_subdir || 'v2-staging' }}

    steps:
      - name: "Checking out repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || '' }}

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12

      - name: Install python deps
        run: |
          pip install -r requirements.txt

      # TODO(amd-justchen): share with build_windows_artifacts.yml. Include in VM image? Dockerfile?
      - name: Install requirements
        run: |
          choco source disable -n=chocolatey
          choco source add -n=internal -s http://10.0.167.96:8081/repository/choco-group/ --priority=1
          choco install --no-progress -y ccache
          # ninja pinned due to a bug in the 1.13.0 release:
          # https://github.com/ninja-build/ninja/issues/2616
          choco install --no-progress -y ninja --version 1.12.1
          choco install --no-progress -y strawberryperl
          echo "$PATH;C:\Strawberry\c\bin" >> $GITHUB_PATH
          choco install --no-progress -y awscli
          choco install --no-progress -y pkgconfiglite
          echo "$PATH;C:\Program Files\Amazon\AWSCLIV2" >> $GITHUB_PATH

      - uses: iterative/setup-dvc@4bdfd2b0f6f1ad7e08afadb03b1a895c352a5239 # v2.0.0
        with:
          version: '3.62.0'

      # After other installs, so MSVC get priority in the PATH.
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

      - name: Runner health status
        run: |
          python ./build_tools/health_status.py

      - name: Setup ccache
        run: |
          python ./build_tools/setup_ccache.py \
            --release-type "${{ env.RELEASE_TYPE }}" \
            --dir "$(dirname $CCACHE_CONFIGPATH)" \
            --local-path "$CACHE_DIR/ccache" \
            --log-dir "${BUILD_DIR}/logs/ccache"

      - name: Fetch sources
        timeout-minutes: 30
        run: |
          git config fetch.parallel 10
          git config --global core.symlinks true
          git config --global core.longpaths true
          python ./build_tools/fetch_sources.py --jobs 12

      - name: Configure Projects
        env:
          cmake_preset: windows-release
          amdgpu_families: ${{ matrix.target_bundle.amdgpu_family }}
          package_version: "ADHOCBUILD"
          extra_cmake_options: ${{ inputs.extra_cmake_options }}
        run: |
          python3 build_tools/github_actions/build_configure.py

      - name: Build therock-artifacts and therock-dist
        run: cmake --build "${{ env.BUILD_DIR }}" --target therock-artifacts therock-dist

      - name: Compress dist folder
        run: |
          cd ${{ env.BUILD_DIR }}/dist/rocm
          echo "Compressing ${{ env.DIST_ARCHIVE }}"
          tar cfz "${{ env.DIST_ARCHIVE }}" --force-local .

      - name: Build Python Packages
        run: |
          python ./build_tools/build_python_packages.py \
            --artifact-dir=${{ env.BUILD_DIR }}/artifacts \
            --dest-dir=${{ env.BUILD_DIR }}/packages \
            --version=${{ needs.setup_metadata.outputs.version }}

      - name: Build report
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          if [ -d "${{ env.BUILD_DIR }}" ]; then
            echo "Build dir:"
            echo "------------"
            ls -lh "${{ env.BUILD_DIR }}"
            echo "CCache Stats:"
            echo "-------------"
            ccache -s -v
          else
            echo "[ERROR] Build directory ${{ env.BUILD_DIR }} does not exist. Skipping report!"
            echo "        This should only happen if the CI is cancelled before the build step."
            exit 1  # Stop the CI as build did not happen
          fi

      - name: Configure AWS Credentials
        if: ${{ github.repository_owner == 'ROCm' && !cancelled() }}
        uses: aws-actions/configure-aws-credentials@99214aa6889fcddfa57764031d71add364327e59 # v6.1.3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-${{ env.RELEASE_TYPE }}
          special-characters-workaround: true

      - name: Push artifacts
        if: ${{ github.repository_owner == 'ROCm' && !cancelled() }}
        run: |
          python build_tools/artifact_manager.py push \
            --run-id ${{ github.run_id }} \
            --build-dir ${{ env.BUILD_DIR }} \
            --stage all

      - name: Post Build Upload
        if: ${{ github.repository_owner == 'ROCm' && !cancelled() }}
        run: |
          python3 build_tools/github_actions/post_build_upload.py \
            --run-id ${{ github.run_id }} \
            --artifact-group "${{ matrix.target_bundle.amdgpu_family }}" \
            --build-dir ${{ env.BUILD_DIR }} \
            --upload \
            --job-status ${{ job.status }}

      - name: Upload Releases to staging S3
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          aws s3 cp ${{ env.BUILD_DIR }}/packages/dist/ s3://${{ env.S3_BUCKET_PY }}/${{ env.S3_STAGING_SUBDIR }}/${{ matrix.target_bundle.amdgpu_family }}/ \
          --recursive --no-follow-symlinks \
          --exclude "*" \
          --include "*.whl" \
          --include "*.tar.gz"

      ## TODO: Restrict uploading to the non-staging S3 directory until sanity checks and all validation tests have successfully passed.
      - name: Upload Releases to S3
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          aws s3 cp ${{ env.DIST_ARCHIVE }} s3://${{ env.S3_BUCKET_TAR }}/${{ env.S3_SUBDIR_TAR }}
          aws s3 cp ${{ env.BUILD_DIR }}/packages/dist/ s3://${{ env.S3_BUCKET_PY }}/${{ env.S3_SUBDIR }}/${{ matrix.target_bundle.amdgpu_family }}/ \
          --recursive --no-follow-symlinks \
          --exclude "*" \
          --include "*.whl" \
          --include "*.tar.gz"

      - name: Trigger building PyTorch wheels
        if: ${{ github.repository_owner == 'ROCm' && matrix.target_bundle.expect_pytorch_failure == false }}
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 # v1.3.2
        with:
          workflow: release_windows_pytorch_wheels.yml
          inputs: |
            { "amdgpu_family": "${{ matrix.target_bundle.amdgpu_family }}",
              "release_type": "${{ env.RELEASE_TYPE }}",
              "s3_subdir": "${{ env.S3_SUBDIR }}",
              "s3_staging_subdir": "${{ env.S3_STAGING_SUBDIR }}",
              "cloudfront_url": "${{ needs.setup_metadata.outputs.cloudfront_url }}",
              "cloudfront_staging_url": "${{ needs.setup_metadata.outputs.cloudfront_staging_url }}",
              "rocm_version": "${{ needs.setup_metadata.outputs.version }}",
              "ref": "${{ inputs.ref || '' }}"
            }
