# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Test JAX Wheels

on:
  workflow_dispatch:
    inputs:
      test_runs_on:
        required: true
        type: string
        default: "linux-gfx942-1gpu-core42-ossci-rocm"
      image_name:
        required: true
        description: JAX docker image to run tests with
        type: string
      jax_version:
        description: Version of JAX to install
        required: false
        type: string
      jax_plugin_branch:
        required: true
        description: JAX plugin branch to checkout
        type: string
        default: "rocm-jaxlib-v0.8.2"

  workflow_call:
    inputs:
      test_runs_on:
        required: true
        type: string
      image_name:
        required: true
        description: JAX docker image to run tests with
        type: string
      jax_version:
        description: Version of JAX to install instead of the one on the docker image
        required: false
        type: string
      jax_plugin_branch:
        description: JAX plugin branch to checkout to use for test scripts
        type: string
        default: "rocm-jaxlib-v0.8.2"

permissions:
  contents: read

jobs:
  test_wheels:
    name: Test
    runs-on: ${{ inputs.test_runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repo: rocm/rocm-jax
      # TODO: Add steps for creating the JAX docker image with an install of TheRock and then running JAX tests on the container
